version: 2
jobs:
  release:
    docker:
      - image: circleci/node:8
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - dependencies-{{ checksum "package-lock.json" }}
          # Fallback
          - dependencies-
      - run: npm install
      - run: npm run build
      - run: npm run semantic-release

workflows:
  version: 2
  release:
    jobs:
      - release:
          filters:
            branches:
              only: master
